on: [push, pull_request]
name: windows tests
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: gcc-latest
      - run: |
          cd tests
          make
        env:
          CC: gcc
          CXX: g++
